name = "campaign-manager-frontend"
main = "src/index.ts"
compatibility_date = "2024-04-28"

[build]
command = "npm install && npm run build"

[deploy]
account_id = "01955bee158eef0e68cad30297e4fa71"

[vars]
NODE_ENV = "production"